### ISSUE TITLE
Properties not always generated in Models

### ISSUE THREAD

**Issue by PaulJoW** [mulesoft-labs/raml-dotnet-tools#113]
Hi,

Quite a lot of my Models do not have properties created for them (it works for some), although the schema information is included. These seem to be objects that include other objects within them.

Is this an issue or is there anything I can do to generate these?
If I create the properties manually, they are written over when the Models/RAML is updated.

I have attached an example where you will see that the ApplicationToEnrol model does not get the Properties generated, however CourseOccurrence does.

[applications.txt](https://github.com/mulesoft-labs/raml-dotnet-tools/files/632881/applications.txt)

Any advice please?
Cheers,
Paul

**Comment by woodp** [comment]
Hi @PaulJoW , thanks for the feedback.

What I get when parsing your file is:

ApplicationToEnrol - Could not parse JSON Schema. Could not resolve schema reference '#/schemas/CourseOccurrence' 

I did 3 changes, added the "id": "CourseOccurrence" to the CourseOcurrence schema, changed the $ref in ApplicationToEnrol to "CourseOcurrence" and changed the order of the schemas so that CourseOcurrence appears before "ApplitationToEnrol"

With those 3 changes I get no warnings.

I attach the file with the changes:
[applications-modified.txt](https://github.com/mulesoft-labs/raml-dotnet-tools/files/633937/applications-modified.txt)

I get these warnings by adding the RAML as a reference. We are not showing these warnings when adding a contract, that is a problem so I will add this as an issue. 
Also, will check to see if I can get rid of the order dependencies issue.

**Comment by woodp** [comment]
Include JSON schema parsing errors/warnings when adding a RAML contract #114

**Comment by PaulJoW** [comment]
Hi Pedro,


Thanks for the quick response.


When I was on my way home last night I had a thought that I would change the order of the Schemas in case there was a dependency chain, and it seems like you confirmed this before I got back to work this morning [😊]

I think the changes you propose would be great additions to the product.


Good work on this tool. It is becoming more useful to me now.


Cheers,

Paul

________________________________
