### ISSUE TITLE
Document how to update Generated Web API interfaces after RAML change

### ISSUE THREAD

**Issue by yesitspeter** [mulesoft-labs/raml-dotnet-tools#116]
It is unclear from the documentation how to initiate the update of previously generated C# WebAPI interfaces.   It seems straightforward to generate interfaces, models, and a controller skeleton.  There is nothing describing how to update them after a change.

**Comment by woodp** [comment]
When you update a RAML contract it will automatically regenerate the code on saving.
This only affects the existing .NET contract interfaces and adds ASP.NET MVC 6 or Web API controller implementations for any new resource in the RAML definition. The existing controller implementations remain untouched.

This is documented here:
https://github.com/mulesoft-labs/raml-dotnet-tools#updating-your-raml-specification

If new resources or methods have been added, the implementation controller won't match the interface.  You will have to implement those methods manually.

In a similar fashion if changes are made to a resource or method and this produces changes in the signature of a method, the interface will be updated but the implementation not. You will have to manually update the signature (and the implementation code).

In the case of deletions the base controllers will no longer route to the implementation method, so it in this case is not absolutely necessary because it will still compile (obsolete implementation code should be removed manually).

Resuming, interfaces and base controllers will be updated automatically, implementation controllers are not changed so they must be updated or deleted manually.

Please let me know if that helped or if something else need clarification.
