### ISSUE TITLE
Update RAML menu option missing in latest version

### ISSUE THREAD

**Issue by tb-wwparker** [mulesoft-labs/raml-dotnet-tools#132]
In older versions of the RAML for .NET client for Visual Studio, after you added a RAML reference, you could update it by right clicking on the RAML file (in the API references section) to rebuild the .cs classes. With the more recent versions of the client, that menu option is missing. I found that if you edit the .ref file and add the path name to the source: key that the menu option comes back.

Could you please fix/restore the Add RAML function to properly save the source path when adding a new RAML file?

**Comment by woodp** [comment]
Hi @tb-wwparker, actually that change is intentional. We decided not to use a harcoded path anymore. When working in a team that path makes no sense except maybe in the original machine.
Now only when the source is an URL that option is available.

Any changes to the RAML file will trigger an update. So if you just edit the RAML file and update the contents that will regenerate the code.

Please let me know if you have any inconvenients using the tools in the way I explained.

**Comment by tb-wwparker** [comment]
@woodp Question for you: The RAMLs that I use are currently hosted on a network file share (so that the filenames are consistent for all dev machines), can I move those RAML files into the actual project itself and when I made edits to the RAML files, edit the files attached to the project rather than the ones on the network file share? 
Second question: once the RAML files are added to the project, does your comment mean that I can edit the RAML files in the API references folders and the system will auto-regenerate the .cs files for me?

**Comment by woodp** [comment]
RAML file/s are copied into the project when adding a RAML reference. The idea is to be able to edit those files directly. But I just checked and this is not working correctly when adding a RAML reference. Will add a separate issue for this.

In the meantime editing the RAML properties and setting the network share on "source" should work for you.
