### ISSUE TITLE
RAMLGen: Add ASP.NET Core Templates

### ISSUE THREAD

**Issue by richardcase** [mulesoft-labs/raml-dotnet-tools#155]
It work be good if RAMLGen had templates for ASP.NET Core.

(In addition to the extension being able to run in VS2017 - issue #136 )

**Comment by woodp** [comment]
There are templates for ASP.Net Core (by default it generates for asp.net core, if you add "-w" it will generate for asp.net web api).

The templates were done some time ago so they import
**Microsoft.AspNet.Mvc;** instead of **Microsoft.AspNetCore.Mvc;**.

For the moment you can replace all **using Microsoft.AspNet.Mvc;** for **using Microsoft.AspNetCore.Mvc;** in the generated code or better directly in the templates.

The templates will be updated for the next release.

**Comment by richardcase** [comment]
Great, thanks for the speedy response.

**Comment by woodp** [comment]
I updated RAMLGen https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/command-line
asp.net core templates were updated
