### ISSUE TITLE
Support for .NET core

### ISSUE THREAD

**Issue by rheyworth** [mulesoft-labs/raml-dotnet-tools#205]
It would be great if the plugin could generate the service and client for .NET core services.

**Comment by guillaume-fr** [comment]
Would be great to have a .net Core [command line interface.](https://github.com/mulesoft-labs/raml-dotnet-tools/tree/master/command-line)

**Comment by rebeccapowell** [comment]
VS2017 with the Mulesoft RAML VSIX instaled. The option to "Enable RAML metadata output" throws the following error when applied to an ASP.NET Core 2.1 kestrel hosted Web API 2 project:

![image](https://user-images.githubusercontent.com/586841/53916145-b8ec2580-4061-11e9-9212-2b4818bfaa04.png)

Followed by:

![image](https://user-images.githubusercontent.com/586841/53916125-a40f9200-4061-11e9-8541-9cc2fa6fed54.png)

Since that feature seems to leverage https://github.com/mulesoft/raml-dotnet-apiexplorer, is it possible to wrokaround this manually?

**Comment by woodp** [comment]
> It would be great if the plugin could generate the service and client for .NET core services.

@rheyworth  The new tools supports asp.net core 2.0 and .net core client too. You can check the beta version here: https://github.com/mulesoft/amf-dotnet-tools/releases/tag/v0.0.1-beta

**Comment by woodp** [comment]
New version supports asp.net core up to 2.2
@rebeccapowell that bug was fixed on the new version
