### ISSUE TITLE
Json type "array" is not understood 

### ISSUE THREAD

**Issue by PabloInNz** [mulesoft-labs/raml-dotnet-tools#48]
If a JSON schema is declared with "type": "array" and the get declaration of the resource body is set to this schema, the code does not recognise it. Instead, a model class is created with the same name as the array schema and another model class is created which has the same members.
e.g. a schema is declared called Product-array
```
Product-array: |
    {
      "type": "array",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "items": {
        "id": "Product",
        "title": "Product",
        "type": "object",
        "properties": {
          "Id": {
            "description": "Primary Key of the Product - unique",
            "type": "number"
          },
          "Code": {
            "description": "Alpha Numeric code for the product",
            "type": "string"
          },
          "Name": {
            "description": "Display name for the product",
            "type": "string"
          },
          "Description": {
            "description": "Additional information explaining the products, clothing and time required",
            "type": "string"
          }
        }
      }
    }
```
This results in model classes being created called "ProductArray.cs" and "ProductsGetOKResponseContent.cs" both with the same members. The ProductsController automatically created comments indicates it expects a return type of `IList<ProductsGetOKResponseContent>` 
I am presuming that the code cannot cope with an array type, which we can change our definition to cope with, but not sure why it creates the new ProductsGetOKResponseContent type ?
If however, an item within the schema is defined as "array" (rather than the schema itself), then this does get translated correctly in the model definition as a property of type `IList<Item>`

If I change the definitions in the .raml file to use the collection and collection-item ResourceTypes and no longer use the "array" schema (as per the RAML 200 example), then the class ProductsGetOKResponseContent.cs is not created. However, a model called ProductsPostRequestContent.cs is created, which is exactly the same as the Departure model created. The Post action looks like this 
```
public IHttpActionResult Post(Models.DeparturesPostRequestContent departurespostrequestcontent)
        {
            // TODO: implement Post - route: departures/
			return Ok();
        }
```
whereas I would expect it to just use Models.Departure as the parameter type. Is there a way to configure this  ? I have found that if I manually change the model type in the ProductsController in the contract to use Models.Departure, it gets overwritten without re-running the "Update RAML contract from source" function, so there seems to be no way of changing it.

**Comment by woodp** [comment]
The generation of two clases with the same properties is a problem related to the javascript parser used to parse the RAML under the hood, in some cases the js parser does not keep the key/name of the json schema which instead gets replaced by the inlined schema. In short there's no way to overcome this with the current javascriot parser.

Nevertheless, there are no problem with array types and since the type created has the same properties as the other type, there is no problem to use this instead of the other. 
If this is not your case then please send the RAML file you are using so we can address the issue.

You cannot change generated classes, these are not made to change. Only the implementation of the controllers underneath the Controllers folder is meant to be modified by hand.

**Comment by PabloInNz** [comment]
OK, thanks for the response.
