### ISSUE TITLE
VS2015 Update1 Support

### ISSUE THREAD

**Issue by jskulavik** [mulesoft-labs/raml-dotnet-tools#57]
Hi Folks,

The solution is failing to build for me with hundreds of errors (too many to list) using Visual Studio 2015 Update1.  The *MuleSoft.RAML.Tools.2015.csproj* implies that if on the correct branch, one should be able to build the solution.  I'm merely trying to find/build the VSIX and use RAML Tools for .NET in VS 2015.  Is support for VS2015 Update1 on the radar?

Thanks for the great RAML toolsets BTW.

**Comment by woodp** [comment]
The extension works fine on VS 2015, have not tried Update 1 yet.

If you want to build, choose the main branch but be sure to use [RAML.NET.v2015.sln]( https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/RAML.NET.v2015.sln)

Otherwise just grab it from the [visual studio gallery](visualstudiogallery.msdn.microsoft.com/cadcb820-762c-4514-9817-884b7558aaa9)

If you still have issues then please let me know.
